name = "premiumsportsai"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "premiumsportsai"
database_id = "ae7df5bf-d66a-4c31-a93d-5f5bd26bbfd9"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "e06e2263794e4393ad5203111d200e0f"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "premiumsportsai-avatars"

[vars]
APP_URL = "https://premiumsportsai.pages.dev"
